require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "node_modules/**/*"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - request
      - controller
      - task
      - lambda

RSpec/MultipleMemoizedHelpers:
  Max: 7
  AllowSubject: true

RSpec/LetSetup:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/MethodCallWithArgsParentheses:
  Enabled: true
