require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/**/*"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - request
      - controller
      - task
      - lambda
